### ISSUE TITLE
When getting an error response from the API, include additional info

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [igeolise/traveltime-platform-qgis-plugin#21]
When receiving an 422 error from the API, it would be useful to see the additional_info.search_id data (https://docs.traveltimeplatform.com/reference/error-response) to work out which search is causing the error. E.g which is the point where there is no data coverage

**Comment by olivierdalang** [comment]
I think this was supposed to be the case already but didn't work for the past few version because of an introduced bug. Should be fixed by https://github.com/igeolise/traveltime-platform-qgis-plugin/commit/96015e6a97aa83cbb65211f35c2fafa14712934f

When clicking in the ocean, you now get this in the error bar
```
Error: Recieved error from the API. Error code : 16 Description : We do not support searches in the given area. Make sure that all points for a search are in the same country See : http://docs.traveltimeplatform.com/reference/error-codes Addtionnal info : search_id: ['departure_searches_1'] locations: ['departure_searches_1'], See log for more details.
```
and this in the message log :
```
2020-06-08T10:31:19     CRITICAL    Error : Recieved error from the API.
             Error code : 16
             Description : We do not support searches in the given area. Make sure that all points for a search are in the same country
             See : http://docs.traveltimeplatform.com/reference/error-codes
             Addtionnal info :
              search_id: ['departure_searches_1']
              locations: ['departure_searches_1'], See log for more details.
```

Is this ok ?
