### ISSUE TITLE
Query  - Which is the timezone used in the parameters?

### ISSUE THREAD

**Issue by gsdali** [igeolise/traveltime-platform-qgis-plugin#5]
I'm guessing UTC and not local, but I would like to confirm.

If they are UTC, could we have a feature to use local timezone?

**Comment by olivierdalang** [comment]
Yes it is UTC.

I agree it's not ideal in terms of UX, but think it's still the best option.

Using local timezones may become quite confusing, as users may then think they can input times relative to their search location. Also you'd get wrong results depending from where you're running an algorithm, which may be very annoying when used e.g. in a processing model.

What do you think ? How exactly would you see this work ?

**Comment by Chris-Hutch-iGeo** [comment]
Could a possible option be to add a new parameter of 'Time Zone' for each tool which then converts the time entered by the user to the corresponding time in UTC - this parameter could default to UTC, but allow the user to change it.

When working in a different time zone, this would probably make the user experience simpler, as they would just choose the time they want (e.g 09:00) and their time zone (e.g UTC+4) and the correct UTC time would be calculated in the background, instead of the user having to work out the correct time in UTC.

**Comment by olivierdalang** [comment]
done (in master).

For the "simplified tools", I added a dropdown, allowing to manually pick the timezone. By default, it's set to the system's time zone.

For the "quick tools", I left as it is, where it uses the local system timezone. I think it's better not to clutter the quick tools settings too much, so that they remain "quick tools".

For the "advanced tools", I also left as is, as the input field is in ISO format, which includes the timezone (e.g. `'2019-09-02T15:00:00+02:00'` specifies UTC+2).
